// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DemoInterfaces.EfCore.Models
{
    public partial class Complaints
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
    }
}