// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DemoInterfaces.EfCore.Models;
using Microsoft.EntityFrameworkCore;
#nullable disable

namespace DemoInterfaces.EfCore.Data
{
    public partial class DemoContext : DbContext
    {
        public DemoContext()
        {
        }

        public DemoContext(DbContextOptions<DemoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.ComplaintsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EmployeeConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
