// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DemoInterfaces.EfCore.Data;
using DemoInterfaces.EfCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DemoInterfaces.EfCore.Data.Configurations
{
    public partial class ComplaintsConfiguration : IEntityTypeConfiguration<Complaints>
    {
        public void Configure(EntityTypeBuilder<Complaints> entity)
        {
            entity.Property(e => e.Description).HasMaxLength(250);

            entity.Property(e => e.Subject).HasMaxLength(250);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Complaints> entity);
    }
}
